import type { NextPage } from "next";
import { getSession } from "next-auth/react";
import Head from "next/head";
import Center from "../src/components/center";
import { Modal } from "../src/components/modal";
import Player from "../src/components/player";
import Sidebar from "../src/components/sidebar";

const Home: NextPage = () => {
  return (
    <div className="bg-black h-screen overflow-hidden">
      <Head>
        <title>Spotify-clone</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Modal />
      <main className="flex">
        <Sidebar />
        <Center />
      </main>

      <div className="sticky bottom-0">
        <Player />
      </div>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  return {
    props: {
      session
    }
  };
};

export default Home;
